# Generated by Django 4.2.2 on 2023-07-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('short_address', models.CharField(max_length=64, verbose_name='Short Address')),
                ('long_address', models.CharField(max_length=128, verbose_name='Long Address')),
                ('building', models.CharField(max_length=64)),
                ('locality', models.CharField(max_length=64)),
                ('landmark', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'db_table': 'user_location',
                'ordering': ['-id'],
            },
        ),
    ]
