# Generated by Django 4.2.2 on 2023-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='long_address',
            field=models.CharField(max_length=512, verbose_name='Long Address'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='short_address',
            field=models.CharField(max_length=256, verbose_name='Short Address'),
        ),
    ]
