# Generated by Django 4.2.2 on 2023-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productquantity',
            constraint=models.UniqueConstraint(fields=('product', 'quantity'), name='unique_product_quantity_mapping'),
        ),
    ]
