# Generated by Django 4.2.2 on 2023-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_cart_unique_user_product_quantity_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity Count'),
        ),
    ]
