# Generated by Django 4.2.2 on 2023-08-03 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cart_quantity_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message="Quantity count can't be less than 1"), django.core.validators.MaxValueValidator(10, message="Quantity count can't be greater than 10")], verbose_name='Quantity Count'),
        ),
    ]
