# Generated by Django 4.2.2 on 2023-08-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_cart_quantity_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
