# Generated by Django 4.2.2 on 2023-08-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquantity',
            options={'ordering': ['quantity__grams'], 'verbose_name': 'Product Quantity', 'verbose_name_plural': 'Product Quantities'},
        ),
    ]
