# Generated by Django 4.2.2 on 2023-07-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_promotionalbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
