# Generated by Django 4.2.2 on 2023-08-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_delete_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('short_address', models.CharField(max_length=256, verbose_name='Short Address')),
                ('long_address', models.CharField(max_length=512, verbose_name='Long Address')),
                ('building', models.CharField(blank=True, max_length=64, null=True)),
                ('locality', models.CharField(blank=True, max_length=64, null=True)),
                ('landmark', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('order_status', models.ForeignKey(limit_choices_to=models.Q(('master_category__name', 'Vendor Status')), on_delete=django.db.models.deletion.CASCADE, related_name='md_order_status', to='common.masterdata', verbose_name='Order Status')),
                ('payment_mode', models.ForeignKey(limit_choices_to=models.Q(('master_category__name', 'Payment Mode')), on_delete=django.db.models.deletion.CASCADE, related_name='md_payment_mode', to='common.masterdata', verbose_name='Payment Mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-id'],
            },
        ),
    ]
