# Generated by Django 4.2.2 on 2023-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivered_at_orderfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='comment',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
