# Generated by Django 4.2.2 on 2023-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderfeedback_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderfeedback',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'user', 'order'), name='unique_content_type_object_user_order_mapping'),
        ),
    ]
