# Generated by Django 4.2.2 on 2023-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderfeedback_unique_content_type_object_user_order_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Delivered At'),
        ),
    ]
