# Generated by Django 4.2.2 on 2023-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_unique_user_product_quantity_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
