# Generated by Django 4.2.2 on 2023-08-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_region'),
        ('order', '0008_alter_order_delivered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_cart_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Discount Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maximum Discount Amount')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Minimun Order Amount')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('coupon_type', models.ForeignKey(limit_choices_to=models.Q(('master_category__name', 'Coupon Type')), on_delete=django.db.models.deletion.CASCADE, to='common.masterdata', verbose_name='Discount Type')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupons Redemptions',
                'db_table': 'coupon_redemption',
                'ordering': ['-id'],
            },
        ),
    ]
