# Generated by Django 4.2.2 on 2023-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_coupon_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(default='Hello world', max_length=256),
            preserve_default=False,
        ),
    ]
